server:
  port: 8888

cloud:
  eureka-host: localhost

spring:
  application:
    name: config-server
  main:
    web-application-type: reactive

  cloud:
    config:
     server:
      git:
        uri: "https://github.com/briansjavablog/micro-services-spring-cloud-config"
        searchPaths: configuration

eureka:
  client:
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka
